### PR TITLE
Include the root element in the enhanced selection

### PR DESCRIPTION
**Pull request by harmenjanssen**
Dang it, I ruined our IE9 compatibility. 😞

### CODE REVIEW

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call(document.childNodes);` and concatenate those?

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call(document.childNodes);` and concatenate those?

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call(document.childNodes);` and concatenate those?

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call(document.childNodes);` and concatenate those?

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call(document.childNodes);` and concatenate those?

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call(document.childNodes);` and concatenate those?

**Comment by schoenkaft** [comment]
> Dang it, I ruined our IE9 compatibility. 😞

And IE10 and IE11. Can't we use something like `Array.prototype.slice.call` and then concatenate them?

**Comment by harmenjanssen** [comment]
Yes, good idea. 
I pushed a fix!

**Comment by harmenjanssen** [comment]
I also flipped them by the way, to have the root first in the collection. 
We don't define an order of execution but it felt sensible to enhance the node itself before its children.

**Pull request merged**
